import React,{useState} from'react';import{createRoot}from'react-dom/client';import{Home,Users,Stethoscope,CalendarDays,Menu,Plus,MapPin,AlertTriangle,IndianRupee}from'lucide-react';import'./styles.css';
const nurses=['Priya R. — Elderly/Wound Care','Jaya S. — Elderly/IV Therapy','Saranya M. — Tracheostomy/PEG'];
function Head({t}){return <header><div><small>HOMECARE</small><h1>{t}</h1></div><i>A</i></header>};function Nav({p,set}){return <nav>{[['dashboard',Home,'Home'],['clients',Users,'Clients'],['nurses',Stethoscope,'Nurses'],['roster',CalendarDays,'Roster'],['more',Menu,'More']].map(([x,I,l])=><button className={p==x?'on':''} onClick={()=>set(x)}><I/><span>{l}</span></button>)}</nav>};
const F=({l,p})=><label>{l}<input placeholder={p||l}/></label>;
function Dashboard({set}){return <><Head t="Admin Dashboard"/><main><section className="hero"><p>Today · 30 September 2026</p><h2>Home Care Operations</h2><div className="stats">{[['28','Active Clients'],['22','Day Shift'],['18','Night Shift'],['2','Vacant Duties']].map(x=><div><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section><h3>Quick actions</h3><div className="quick"><button onClick={()=>set('enquiry')}><Plus/>New Enquiry</button><button onClick={()=>set('newclient')}><Users/>New Client</button><button onClick={()=>set('roster')}><CalendarDays/>Assign Nurse</button><button onClick={()=>set('accounts')}><IndianRupee/>Receive Payment</button></div><h3>Needs attention</h3><article><AlertTriangle/><div><b>2 vacant duties</b><p>Tomorrow's roster needs assignment.</p></div></article></main></>}
function Enquiry({set}){return <><Head t="New Enquiry"/><main><form><F l="Caller Name *"/><F l="Relationship *"/><F l="Mobile Number *"/><F l="Client Name *"/><F l="Area / Location *"/><label>Service Required<select><option>Day Shift</option><option>Night Shift</option><option>Day + Night</option><option>Single Visit</option></select></label><F l="Required From" p="dd-mm-yyyy"/><label>Clinical Requirement<textarea/></label><button type="button" className="primary" onClick={()=>set('newclient')}>Save & Convert to Client</button></form></main></>}
function Clients({set}){return <><Head t="Clients"/><main><button className="primary full" onClick={()=>set('newclient')}><Plus/> New Client</button>{['Lakshmi — Anna Nagar — Day + Night','Raman — Mogappair — Day Shift'].map((x,i)=><article><div><b>{x}</b><p>HC-2026-000{i+1} · Active</p></div><button onClick={()=>set('service')}>Open</button></article>)}</main></>}
function NewClient({set}){return <><Head t="Client Registration"/><main><div className="steps">1 Personal · 2 Medical · 3 Family · 4 Service</div><form><F l="Client Name *"/><F l="DOB / Age *"/><F l="Mobile Number"/><F l="Full Address *"/><F l="Area / Landmark *"/><button type="button"><MapPin/> Capture Home Location</button><h3>Medical</h3><F l="Primary Diagnosis / Condition *"/><F l="Previous / Recent Hospital"/><F l="Treating Doctor"/><h3>Primary Family Contact</h3><F l="Name *"/><F l="Relationship *"/><F l="Mobile / WhatsApp *"/><h3>Secondary Family Contact</h3><F l="Name"/><F l="Relationship"/><F l="Mobile / WhatsApp"/><button type="button" className="primary" onClick={()=>set('service')}>Save & Continue</button></form></main></>}
function Service({set}){return <><Head t="Start Service"/><main><article><div><small>CLIENT</small><h2>Lakshmi</h2><p>HC-2026-0001 · Anna Nagar</p></div></article><form><label>Service Type<select><option>Day + Night</option><option>Day Shift</option><option>Night Shift</option><option>Single Visit</option></select></label><F l="Start Date" p="01-10-2026"/><F l="Day Rate" p="₹ 1,500"/><F l="Night Rate" p="₹ 1,700"/><div className="total"><span>Daily Charge</span><b>₹3,200</b></div><F l="Advance Received" p="₹ 10,000"/><button type="button" className="primary" onClick={()=>set('roster')}>Start Service</button></form></main></>}
function Roster({set}){let D=({c,n,night})=><article><div><small>{night?'NIGHT · 7 PM–7 AM':'DAY · 7 AM–7 PM'}</small><b>{c}</b></div>{n?<span className="pill">{n}</span>:<button className="danger" onClick={()=>set('assign')}>VACANT</button>}</article>;return <><Head t="Duty Roster"/><main><div className="date">‹ <b>01 OCT 2026</b> ›</div><D c="Lakshmi" n="Priya R."/><D c="Raman" n="Jaya S."/><D c="Joseph"/><D c="Lakshmi" n="Saranya M." night/><D c="Raman" night/></main></>}
function Assign({set}){return <><Head t="Assign Nurse"/><main><article><div><b>Joseph · Day Shift</b><p>01-10-2026 · 7 AM–7 PM</p></div></article><h3>Available nurses</h3>{nurses.map(n=><article><div><b>{n.split(' — ')[0]}</b><p>{n.split(' — ')[1]}</p></div><button onClick={()=>set('roster')}>Assign</button></article>)}</main></>}
function Empty({t}){return <><Head t={t}/><main><div className="empty"><h2>{t}</h2><p>Reserved in the Phase-1 architecture. Supabase connection will plug into this module next.</p></div></main></>}
function App(){let[p,set]=useState('dashboard');let x={dashboard:<Dashboard set={set}/>,enquiry:<Enquiry set={set}/>,clients:<Clients set={set}/>,newclient:<NewClient set={set}/>,service:<Service set={set}/>,roster:<Roster set={set}/>,assign:<Assign set={set}/>,nurses:<Empty t="Nurses"/>,accounts:<Empty t="Accounts & Payments"/>,more:<Empty t="More"/>};return <div className="app">{x[p]}{!['enquiry','newclient','service','assign'].includes(p)&&<Nav p={p} set={set}/>}</div>}createRoot(document.getElementById('root')).render(<App/>);
